server:
  port: 8010

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XzibiT-Collins/ByteBite-configs
          default-label: main
  application:
    name: config-server